// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { VestingWallet$Type } from "./VestingWallet";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["VestingWallet"]: VestingWallet$Type;
    ["@openzeppelin/contracts/finance/VestingWallet.sol:VestingWallet"]: VestingWallet$Type;
  }

  interface ContractTypesMap {
    ["VestingWallet"]: GetContractReturnType<VestingWallet$Type["abi"]>;
    ["@openzeppelin/contracts/finance/VestingWallet.sol:VestingWallet"]: GetContractReturnType<VestingWallet$Type["abi"]>;
  }
}
