// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ExampleToken$Type } from "./ExampleToken";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ExampleToken"]: ExampleToken$Type;
    ["contracts/ExampleToken.sol:ExampleToken"]: ExampleToken$Type;
  }

  interface ContractTypesMap {
    ["ExampleToken"]: GetContractReturnType<ExampleToken$Type["abi"]>;
    ["contracts/ExampleToken.sol:ExampleToken"]: GetContractReturnType<ExampleToken$Type["abi"]>;
  }
}
