// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface Address$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "Address",
  "sourceName": "@openzeppelin/contracts/utils/Address.sol",
  "abi": [
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "target",
          "type": "address"
        }
      ],
      "name": "AddressEmptyCode",
      "type": "error"
    }
  ],
  "bytecode": "0x60808060405234601757603a9081601d823930815050f35b600080fdfe600080fdfea26469706673582212201f98aa213073847cfdf46f4886b29bb00675a97cd9e16da77d60c69caa9ae7fe64736f6c634300081b0033",
  "deployedBytecode": "0x600080fdfea26469706673582212201f98aa213073847cfdf46f4886b29bb00675a97cd9e16da77d60c69caa9ae7fe64736f6c634300081b0033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "Address",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Address$Type["abi"]>>;
  export function deployContract(
    contractName: "@openzeppelin/contracts/utils/Address.sol:Address",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Address$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "Address",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Address$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@openzeppelin/contracts/utils/Address.sol:Address",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Address$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "Address",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Address$Type["abi"]>>;
  export function getContractAt(
    contractName: "@openzeppelin/contracts/utils/Address.sol:Address",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Address$Type["abi"]>>;
}
