// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ExampleVestingVault$Type } from "./ExampleVestingVault";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ExampleVestingVault"]: ExampleVestingVault$Type;
    ["contracts/ExampleVestingVault.sol:ExampleVestingVault"]: ExampleVestingVault$Type;
  }

  interface ContractTypesMap {
    ["ExampleVestingVault"]: GetContractReturnType<ExampleVestingVault$Type["abi"]>;
    ["contracts/ExampleVestingVault.sol:ExampleVestingVault"]: GetContractReturnType<ExampleVestingVault$Type["abi"]>;
  }
}
