// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { MockAggregatorV3$Type } from "./MockAggregatorV3";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["MockAggregatorV3"]: MockAggregatorV3$Type;
    ["contracts/MockAggregatorV3.sol:MockAggregatorV3"]: MockAggregatorV3$Type;
  }

  interface ContractTypesMap {
    ["MockAggregatorV3"]: GetContractReturnType<MockAggregatorV3$Type["abi"]>;
    ["contracts/MockAggregatorV3.sol:MockAggregatorV3"]: GetContractReturnType<MockAggregatorV3$Type["abi"]>;
  }
}
