// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ExampleVestingWallet$Type } from "./ExampleVestingWallet";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ExampleVestingWallet"]: ExampleVestingWallet$Type;
    ["contracts/ExampleVestingWallet.sol:ExampleVestingWallet"]: ExampleVestingWallet$Type;
  }

  interface ContractTypesMap {
    ["ExampleVestingWallet"]: GetContractReturnType<ExampleVestingWallet$Type["abi"]>;
    ["contracts/ExampleVestingWallet.sol:ExampleVestingWallet"]: GetContractReturnType<ExampleVestingWallet$Type["abi"]>;
  }
}
