// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ExampleCrowdSale$Type } from "./ExampleCrowdSale";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ExampleCrowdSale"]: ExampleCrowdSale$Type;
    ["contracts/ExampleCrowdSale.sol:ExampleCrowdSale"]: ExampleCrowdSale$Type;
  }

  interface ContractTypesMap {
    ["ExampleCrowdSale"]: GetContractReturnType<ExampleCrowdSale$Type["abi"]>;
    ["contracts/ExampleCrowdSale.sol:ExampleCrowdSale"]: GetContractReturnType<ExampleCrowdSale$Type["abi"]>;
  }
}
